version: '3.6'
services:
  api:
    container_name: emall-cont
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    environment:
      - JWT_TOKEN_SECRET=ajsonwebtokensecret
      - MONGO_URI=mongodb://mongo:27017/emall
      - PORT=3005
      - MAIL_USER=tegaokem@gmail.com
      - MAIL_PASS=11861538da
      - FORGOT_PASS_EMAIL=noreply@garahub.com
      - CLIENT_SIDE_URL=http://localhost:3001
      - ELASTICSEARCH_URI=http://elasticsearch:9200
    volumes:
      - /app/node_modules
      - .:/app
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - mongo
    networks:
      - esnet
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - esnet
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - esnet
volumes:
  esdata:
networks:
  esnet:
